# app/config/routes.yaml

app_activite_front:
    path: /activites
    controller: App\Controller\ActiviteController::front
    methods: GET

pdf_generate:
    path: '/generate-pdf'
    controller: App\Controller\PdfController::generatePdf
